### ISSUE TITLE
Add project slug validation according to provider limitation.

### ISSUE THREAD

**Issue by filippo-20tab** [20tab/20tab-standard-project#179]
Apparently, some DigitalOcean resources have a limit on the length of their names (e.g. 40 chars for database user). Let's discuss the introduction of some validation in `setup.py`.

**Comment by niccolomineo** [comment]
Can we make a legitimate assumption on what the max length could be for projects? I’d say 25 is plenty. 

Else, is there a way to purposely make an empty call to DO and output the grepped error?

**Comment by filippo-20tab** [comment]
Tracked internally by 20tab.
